# Conexões locais
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Permitir containers Docker no servidor 1
host    all             all             172.17.0.0/16           md5

# Permitir acesso do servidor 2
host    reserve_database reserve_user   192.168.1.216/32        md5
host    all              replicator     192.168.1.216/32        md5
