# Conexões locais
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Permitir que o servidor 1 envie dados para replicação
host    reserve_database reserve_user   192.168.1.93/32         md5
